#INCLUDE 'protheus.ch'
#INCLUDE 'parmtype.ch'

/*/{Protheus.doc} ADVPL11
// TODO INFORMAR DESCRIÇÃO
@TYPE function
@AUTHOR Guilherme Bigois
@SINCE 14/11/2017
@VERSION P12
@RETURN NIL
/*/

USER FUNCTION ADVPL11()

RETURN