// DESCRIÇÃO:		PRIMEIRAS INTERAÇÕES COM A LINGUAGEM ADVPL
// AUTOR:			GUILHERME BIGOIS

User Function intro01()

// DECLARAÇÃO DE CONSTANTE
Local _cVar := 'GUILHERME'

// TESTE CONDICIONAL SIMPLES
If _cVar == 'GUILHERME'
	alert('NOME CORRETO')
Else
	alert('NOME INCORRETO')
Endif

Return